openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/v1/ambassadors/:
    get:
      operationId: api_v1_ambassadors_list
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AmbassadorRead'
          description: ''
    post:
      operationId: api_v1_ambassadors_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmbassadorCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AmbassadorCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AmbassadorCreateRequest'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmbassadorCreate'
          description: ''
  /api/v1/ambassadors/{id}/:
    get:
      operationId: api_v1_ambassadors_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Амбассадор.
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmbassadorRead'
          description: ''
    put:
      operationId: api_v1_ambassadors_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Амбассадор.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmbassadorCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AmbassadorCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AmbassadorCreateRequest'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmbassadorCreate'
          description: ''
    patch:
      operationId: api_v1_ambassadors_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Амбассадор.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedAmbassadorCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedAmbassadorCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedAmbassadorCreateRequest'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmbassadorCreate'
          description: ''
    delete:
      operationId: api_v1_ambassadors_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Амбассадор.
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/api/schema/:
    get:
      operationId: api_v1_api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/v1/auth/token/login/:
    post:
      operationId: api_v1_auth_token_login_create
      description: Use this endpoint to obtain user authentication token.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenCreateRequest'
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenCreate'
          description: ''
  /api/v1/auth/token/logout/:
    post:
      operationId: api_v1_auth_token_logout_create
      description: Use this endpoint to logout user (remove user authentication token).
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /api/v1/content/:
    get:
      operationId: api_v1_content_list
      description: Возвращает пагинированный список объектов контента с возможностью
        фильтрации по статусу и поиска по имени.
      summary: Получение списка контента
      parameters:
      - in: query
        name: full_name
        schema:
          type: string
        description: Поиск по имени и фамилии
      - in: query
        name: limit
        schema:
          type: integer
        description: Лимит объектов на странице
      - in: query
        name: offset
        schema:
          type: integer
        description: Смещение от начала списка
      - in: query
        name: status
        schema:
          type: string
        description: Статус контента для фильтрации
        examples:
          New:
            value: new
            summary: new
          Approved:
            value: approved
            summary: approved
          Rejected:
            value: rejected
            summary: rejected
      tags:
      - api
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedContentList'
          description: ''
    post:
      operationId: api_v1_content_create
      description: Создает новый объект контента с данными, предоставленными в запросе.
      summary: Создание нового объекта контента
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentRequest'
            examples:
              ПримерСозданияКонтента:
                value:
                  full_name: Иван Иванов
                  telegram: '@ivanivanov'
                  link: http://example.com/content
                  guide: true
                summary: Пример запроса на создание контента
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ContentRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ContentRequest'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
              examples:
                ПримерОтветаНаСозданиеКонтента:
                  value:
                    id: 1
                    full_name: Иван Иванов
                    telegram: '@ivanivanov'
                    link: http://example.com/content
                    guide: true
                    status: new
                    created_date: '2024-03-03'
                    ambassador: 1
                  summary: Пример ответа на создание контента
          description: ''
  /api/v1/content/{id}/:
    get:
      operationId: api_v1_content_retrieve
      description: |-
        Viewset для модели Контента
        Позволяет фильтровать выборку по полям status и full_name.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Контент.
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ''
    patch:
      operationId: api_v1_content_partial_update
      description: Обновляет часть данных объекта контента с указанным ID. Использовать
        для обновления статуса
      summary: Частичное обновление объекта контента
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Контент.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedContentRequest'
            examples:
              ПримерОбновленияСтатусаКонтента:
                value:
                  status: rejected
                summary: Пример запроса на обновления статуса контента
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedContentRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedContentRequest'
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
              examples:
                ПримерОбновленияСтатусаКонтента:
                  value:
                    id: 1
                    full_name: Иван Иванов
                    telegram: '@ivanivanov'
                    link: http://example.com/content
                    guide: true
                    status: rejected
                    created_date: '2024-03-03'
                    ambassador: 1
                  summary: Пример ответа на обновления статуса контента
          description: ''
  /api/v1/promocodes/:
    get:
      operationId: api_v1_promocodes_list
      tags:
      - api
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PromoCode'
          description: ''
    post:
      operationId: api_v1_promocodes_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromoCodeRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PromoCodeRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PromoCodeRequest'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromoCode'
          description: ''
  /api/v1/promocodes/{id}/:
    get:
      operationId: api_v1_promocodes_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Промокод.
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromoCode'
          description: ''
    put:
      operationId: api_v1_promocodes_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Промокод.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromoCodeRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PromoCodeRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PromoCodeRequest'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromoCode'
          description: ''
    patch:
      operationId: api_v1_promocodes_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Промокод.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPromoCodeRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPromoCodeRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPromoCodeRequest'
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromoCode'
          description: ''
    delete:
      operationId: api_v1_promocodes_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Промокод.
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    AmbassadorCreate:
      type: object
      description: Сериализатор для создания амбассадоров.
      properties:
        id:
          type: integer
          readOnly: true
        full_name:
          type: string
          title: Полное имя
          maxLength: 255
        gender:
          allOf:
          - $ref: '#/components/schemas/GenderEnum'
          title: Пол
        country:
          type: string
          title: Страна
          maxLength: 100
        city:
          type: string
          title: Город
          maxLength: 100
        address:
          type: string
          title: Адрес проживания
          maxLength: 255
        postal_code:
          type: string
          title: Индекс
          maxLength: 20
        email:
          type: string
          title: Адрес проживания
          maxLength: 255
        phone_number:
          type: string
          title: Номер телефона
          maxLength: 20
        telegram:
          type: string
          title: Ник в телеграме
          maxLength: 100
        edu:
          type: string
          title: Образование
          maxLength: 1000
        work:
          type: string
          title: Место работы
          maxLength: 1000
        study_goal:
          type: string
          title: Цель обучения
          maxLength: 1000
        blog_url:
          type: string
          nullable: true
          title: Ссылка на блоги
          maxLength: 255
        clothing_size:
          allOf:
          - $ref: '#/components/schemas/ClothingSizeEnum'
          title: Размер одежды
        shoe_size:
          type: string
          title: Размер обуви
          maxLength: 50
        additional_comments:
          type: string
          nullable: true
          title: Дополнительная информация
          maxLength: 2000
        status:
          allOf:
          - $ref: '#/components/schemas/Status096Enum'
          title: Статус амбассадора
        reg_date:
          type: string
          format: date-time
          readOnly: true
          title: Дата регистрации
        ya_edu:
          type: integer
          nullable: true
          title: Программа обучения
        amb_goals:
          type: array
          items:
            type: integer
            title: Цель амбассадорства
          title: Цель амбассадорства
      required:
      - address
      - amb_goals
      - city
      - clothing_size
      - country
      - edu
      - email
      - full_name
      - gender
      - id
      - phone_number
      - postal_code
      - reg_date
      - shoe_size
      - study_goal
      - telegram
      - work
    AmbassadorCreateRequest:
      type: object
      description: Сериализатор для создания амбассадоров.
      properties:
        full_name:
          type: string
          minLength: 1
          title: Полное имя
          maxLength: 255
        gender:
          allOf:
          - $ref: '#/components/schemas/GenderEnum'
          title: Пол
        country:
          type: string
          minLength: 1
          title: Страна
          maxLength: 100
        city:
          type: string
          minLength: 1
          title: Город
          maxLength: 100
        address:
          type: string
          minLength: 1
          title: Адрес проживания
          maxLength: 255
        postal_code:
          type: string
          minLength: 1
          title: Индекс
          maxLength: 20
        email:
          type: string
          minLength: 1
          title: Адрес проживания
          maxLength: 255
        phone_number:
          type: string
          minLength: 1
          title: Номер телефона
          maxLength: 20
        telegram:
          type: string
          minLength: 1
          title: Ник в телеграме
          maxLength: 100
        edu:
          type: string
          minLength: 1
          title: Образование
          maxLength: 1000
        work:
          type: string
          minLength: 1
          title: Место работы
          maxLength: 1000
        study_goal:
          type: string
          minLength: 1
          title: Цель обучения
          maxLength: 1000
        blog_url:
          type: string
          nullable: true
          title: Ссылка на блоги
          maxLength: 255
        clothing_size:
          allOf:
          - $ref: '#/components/schemas/ClothingSizeEnum'
          title: Размер одежды
        shoe_size:
          type: string
          minLength: 1
          title: Размер обуви
          maxLength: 50
        additional_comments:
          type: string
          nullable: true
          title: Дополнительная информация
          maxLength: 2000
        status:
          allOf:
          - $ref: '#/components/schemas/Status096Enum'
          title: Статус амбассадора
        ya_edu:
          type: integer
          nullable: true
          title: Программа обучения
        amb_goals:
          type: array
          items:
            type: integer
            title: Цель амбассадорства
          title: Цель амбассадорства
      required:
      - address
      - amb_goals
      - city
      - clothing_size
      - country
      - edu
      - email
      - full_name
      - gender
      - phone_number
      - postal_code
      - shoe_size
      - study_goal
      - telegram
      - work
    AmbassadorGoal:
      type: object
      description: Сериализатор для целей амбассадорства.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название цели
          maxLength: 255
      required:
      - id
      - name
    AmbassadorRead:
      type: object
      description: Сериализатор для чтения амбассадоров.
      properties:
        id:
          type: integer
          readOnly: true
        ya_edu:
          $ref: '#/components/schemas/TrainingProgram'
        amb_goals:
          type: array
          items:
            $ref: '#/components/schemas/AmbassadorGoal'
        promo_code:
          type: string
          readOnly: true
        full_name:
          type: string
          title: Полное имя
          maxLength: 255
        gender:
          allOf:
          - $ref: '#/components/schemas/GenderEnum'
          title: Пол
        country:
          type: string
          title: Страна
          maxLength: 100
        city:
          type: string
          title: Город
          maxLength: 100
        address:
          type: string
          title: Адрес проживания
          maxLength: 255
        postal_code:
          type: string
          title: Индекс
          maxLength: 20
        email:
          type: string
          title: Адрес проживания
          maxLength: 255
        phone_number:
          type: string
          title: Номер телефона
          maxLength: 20
        telegram:
          type: string
          title: Ник в телеграме
          maxLength: 100
        edu:
          type: string
          title: Образование
          maxLength: 1000
        work:
          type: string
          title: Место работы
          maxLength: 1000
        study_goal:
          type: string
          title: Цель обучения
          maxLength: 1000
        blog_url:
          type: string
          nullable: true
          title: Ссылка на блоги
          maxLength: 255
        clothing_size:
          allOf:
          - $ref: '#/components/schemas/ClothingSizeEnum'
          title: Размер одежды
        shoe_size:
          type: string
          title: Размер обуви
          maxLength: 50
        additional_comments:
          type: string
          nullable: true
          title: Дополнительная информация
          maxLength: 2000
        status:
          allOf:
          - $ref: '#/components/schemas/Status096Enum'
          title: Статус амбассадора
        reg_date:
          type: string
          format: date-time
          readOnly: true
          title: Дата регистрации
      required:
      - address
      - amb_goals
      - city
      - clothing_size
      - country
      - edu
      - email
      - full_name
      - gender
      - id
      - phone_number
      - postal_code
      - promo_code
      - reg_date
      - shoe_size
      - study_goal
      - telegram
      - work
      - ya_edu
    ClothingSizeEnum:
      enum:
      - XS
      - S
      - M
      - L
      - XL
      type: string
      description: |-
        * `XS` - XS
        * `S` - S
        * `M` - M
        * `L` - L
        * `XL` - XL
    Content:
      type: object
      description: Сериализатор для модели Контента.
      properties:
        id:
          type: integer
          readOnly: true
        full_name:
          type: string
          title: Имя и Фамилия
          maxLength: 255
        telegram:
          type: string
          title: Ник в телеграме
          maxLength: 100
        link:
          type: string
          title: Ссылка на контент
          maxLength: 200
        guide:
          type: boolean
          title: В рамках Гайда?
        status:
          allOf:
          - $ref: '#/components/schemas/ContentStatusEnum'
          title: Статус контента
        created_date:
          type: string
          format: date
          readOnly: true
          title: Дата создания
        ambassador:
          type: integer
          nullable: true
      required:
      - created_date
      - full_name
      - guide
      - id
      - link
      - telegram
    ContentRequest:
      type: object
      description: Сериализатор для модели Контента.
      properties:
        full_name:
          type: string
          minLength: 1
          title: Имя и Фамилия
          maxLength: 255
        telegram:
          type: string
          minLength: 1
          title: Ник в телеграме
          maxLength: 100
        link:
          type: string
          minLength: 1
          title: Ссылка на контент
          maxLength: 200
        guide:
          type: boolean
          title: В рамках Гайда?
        status:
          allOf:
          - $ref: '#/components/schemas/ContentStatusEnum'
          title: Статус контента
        ambassador:
          type: integer
          nullable: true
      required:
      - full_name
      - guide
      - link
      - telegram
    ContentStatusEnum:
      enum:
      - new
      - approved
      - rejected
      type: string
      description: |-
        * `new` - Новая публикация
        * `approved` - Одобрена
        * `rejected` - Не одобрена
    GenderEnum:
      enum:
      - М
      - Ж
      type: string
      description: |-
        * `М` - Мужской
        * `Ж` - Женский
    PaginatedContentList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Content'
    PatchedAmbassadorCreateRequest:
      type: object
      description: Сериализатор для создания амбассадоров.
      properties:
        full_name:
          type: string
          minLength: 1
          title: Полное имя
          maxLength: 255
        gender:
          allOf:
          - $ref: '#/components/schemas/GenderEnum'
          title: Пол
        country:
          type: string
          minLength: 1
          title: Страна
          maxLength: 100
        city:
          type: string
          minLength: 1
          title: Город
          maxLength: 100
        address:
          type: string
          minLength: 1
          title: Адрес проживания
          maxLength: 255
        postal_code:
          type: string
          minLength: 1
          title: Индекс
          maxLength: 20
        email:
          type: string
          minLength: 1
          title: Адрес проживания
          maxLength: 255
        phone_number:
          type: string
          minLength: 1
          title: Номер телефона
          maxLength: 20
        telegram:
          type: string
          minLength: 1
          title: Ник в телеграме
          maxLength: 100
        edu:
          type: string
          minLength: 1
          title: Образование
          maxLength: 1000
        work:
          type: string
          minLength: 1
          title: Место работы
          maxLength: 1000
        study_goal:
          type: string
          minLength: 1
          title: Цель обучения
          maxLength: 1000
        blog_url:
          type: string
          nullable: true
          title: Ссылка на блоги
          maxLength: 255
        clothing_size:
          allOf:
          - $ref: '#/components/schemas/ClothingSizeEnum'
          title: Размер одежды
        shoe_size:
          type: string
          minLength: 1
          title: Размер обуви
          maxLength: 50
        additional_comments:
          type: string
          nullable: true
          title: Дополнительная информация
          maxLength: 2000
        status:
          allOf:
          - $ref: '#/components/schemas/Status096Enum'
          title: Статус амбассадора
        ya_edu:
          type: integer
          nullable: true
          title: Программа обучения
        amb_goals:
          type: array
          items:
            type: integer
            title: Цель амбассадорства
          title: Цель амбассадорства
    PatchedContentRequest:
      type: object
      description: Сериализатор для модели Контента.
      properties:
        full_name:
          type: string
          minLength: 1
          title: Имя и Фамилия
          maxLength: 255
        telegram:
          type: string
          minLength: 1
          title: Ник в телеграме
          maxLength: 100
        link:
          type: string
          minLength: 1
          title: Ссылка на контент
          maxLength: 200
        guide:
          type: boolean
          title: В рамках Гайда?
        status:
          allOf:
          - $ref: '#/components/schemas/ContentStatusEnum'
          title: Статус контента
        ambassador:
          type: integer
          nullable: true
    PatchedPromoCodeRequest:
      type: object
      description: Сериализатор для модели промокода.
      properties:
        name:
          type: string
          minLength: 1
          title: Промокод
          maxLength: 255
        status:
          allOf:
          - $ref: '#/components/schemas/PromoCodeStatusEnum'
          title: Статус промокода
        ambassador:
          type: integer
          title: Амбассадор
    PromoCode:
      type: object
      description: Сериализатор для модели промокода.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Промокод
          maxLength: 255
        status:
          allOf:
          - $ref: '#/components/schemas/PromoCodeStatusEnum'
          title: Статус промокода
        ambassador:
          type: integer
          title: Амбассадор
      required:
      - ambassador
      - id
      - name
    PromoCodeRequest:
      type: object
      description: Сериализатор для модели промокода.
      properties:
        name:
          type: string
          minLength: 1
          title: Промокод
          maxLength: 255
        status:
          allOf:
          - $ref: '#/components/schemas/PromoCodeStatusEnum'
          title: Статус промокода
        ambassador:
          type: integer
          title: Амбассадор
      required:
      - ambassador
      - name
    PromoCodeStatusEnum:
      enum:
      - active
      - inactive
      type: string
      description: |-
        * `active` - Активный
        * `inactive` - Неактивный
    Status096Enum:
      enum:
      - active
      - paused
      - not_ambassador
      - pending
      type: string
      description: |-
        * `active` - Активный
        * `paused` - На паузе
        * `not_ambassador` - Не амбассадор
        * `pending` - Уточняется
    TokenCreate:
      type: object
      properties:
        password:
          type: string
        username:
          type: string
    TokenCreateRequest:
      type: object
      properties:
        password:
          type: string
          minLength: 1
        username:
          type: string
          minLength: 1
    TrainingProgram:
      type: object
      description: Сериализатор для программ обучения.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название программы
          maxLength: 255
      required:
      - id
      - name
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
